require 'ronin/web/extensions/nokogiri/xml/node'
require 'ronin/web/extensions/nokogiri/xml/text'
require 'ronin/web/extensions/nokogiri/xml/attr'
require 'ronin/web/extensions/nokogiri/xml/element'
require 'ronin/web/extensions/nokogiri/xml/document'
