FROM ruby:<%= @ruby_version -%>

RUN apt-get update -qq -y && gem update bundler

WORKDIR /app
COPY . /app
RUN bundle install

EXPOSE <%= @port -%>

CMD ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "<%= @port -%>"]
